### PR TITLE
Add schema error handling in addMany function

### PR DESCRIPTION
**Pull request by jakbin**

### CODE REVIEW

**Comment by jakbin** [comment]
@Adwaith-Rajesh

**Comment by jakbin** [comment]
@Adwaith-Rajesh please review this pull request ?

**Comment by Adwaith-Rajesh** [comment]
assume that I want to add the following data.

```python
data = [
     {"name": "name1", "age": 3},
     {"name": "name2", "age": 4},
     {"name": "name3", "test": 3},
     {"name": "name4", "age": 3},
     {"name": "name5", "age": 3},
]
```

Here the first line sets the schema to be `name, age`. The second line goes in without any issues, then the third data point should raise an Error, according to your PR. This prevents the last two from being inserted into the DB.

So, how do you rationalize this?, In a collection of data points that needs to be inserted into the DB, If a data point in the middle raised an error, You prevent all the data succeeding from being inserted into the DB, but the preceding data points are allowed in. It doesn't make sense dude.

**Comment by jakbin** [comment]
i also think about that

py1

then i check test.json file

py2

then add data given by you

py3

then i again check test.json file 

py4

But no added in test.json file.

**Comment by Adwaith-Rajesh** [comment]
Okay, my mistake then, next time write a small description about ur code change

**Comment by jakbin** [comment]
> Okay, my mistake then, next time write a small description about ur code change

Ok

**Pull request merged**
